document.addEventListener('DOMContentLoaded', () => {
    const generateBtn = document.getElementById('generate-btn');
    const recipeOutput = document.getElementById('recipe-output');

    generateBtn.addEventListener('click', async () => {
        const apiKey = "AIzaSyArXV8E_4tnmFhx6lIVIfbluSCYZHmAZX8"; // User will insert their key here
        const i1 = document.getElementById('ing-1').value.trim();
        const i2 = document.getElementById('ing-2').value.trim();
        const i3 = document.getElementById('ing-3').value.trim();

        const ingredients = [i1, i2, i3].filter(v => v !== '');

        if (ingredients.length < 3) {
            alert('Please provide exactly 3 ingredients to synthesize a recipe.');
            return;
        }

        // Start loading state
        generateBtn.classList.add('btn-loading');
        generateBtn.disabled = true;
        recipeOutput.classList.add('hidden');

        try {
            const recipeData = await generateWithGemini(apiKey, ingredients);
            renderRecipe(recipeData);

            // Scroll to recipe
            setTimeout(() => {
                recipeOutput.scrollIntoView({ behavior: 'smooth', block: 'start' });
            }, 100);
        } catch (error) {
            alert('Error generating recipe: ' + error.message);
        } finally {
            generateBtn.classList.remove('btn-loading');
            generateBtn.disabled = false;
        }
    });

    async function generateWithGemini(apiKey, ingredients) {
        const promptText = `
You are the "Leftover Chef" Logic Engine, an expert culinary architect specialized in zero-waste recipe generation.

Objective:
Input: ${ingredients.join(', ')}

Output a creative recipe name and detailed instructions utilizing ONLY these 3 ingredients and up to 2 pantry staples (salt, oil, water, etc). Exclude toxic combinations.

Respond ONLY with a valid JSON object matching this exact schema:
{
  "display_output": {
    "title": "Recipe Name Here",
    "ingredients_used": "Ingredient 1, Ingredient 2, Ingredient 3",
    "difficulty": "Easy/Medium/Hard",
    "estimated_time": "15 mins",
    "instructions": [
      "Step 1: ...",
      "Step 2: ...",
      "Step 3: ...",
      "Step 4: ..."
    ],
    "chef_note": "A tip on why this works."
  }
}
`;

        const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                contents: [{
                    parts: [{ text: promptText }]
                }],
                generationConfig: {
                    temperature: 0.7,
                    responseMimeType: "application/json"
                }
            })
        });

        if (!response.ok) {
            const err = await response.json();
            throw new Error(err.error?.message || 'Failed to fetch from Gemini');
        }

        const data = await response.json();
        const jsonText = data.candidates[0].content.parts[0].text;
        return JSON.parse(jsonText);
    }

    function renderRecipe(data) {
        const { display_output } = data;

        recipeOutput.innerHTML = `
            <div class="recipe-header">
                <div class="recipe-meta" style="margin-bottom: 1.5rem; color: var(--accent); font-weight: 600;">
                    <span style="display:inline-flex; align-items:center; gap:8px;">
                        <span style="width:10px; height:10px; background:#8b5cf6; border-radius:50%; box-shadow: 0 0 10px #8b5cf6;"></span> 
                        GENERATED BY GEMINI AI
                    </span>
                </div>
                <h2 class="recipe-title">${display_output.title}</h2>
                <div class="recipe-meta">
                    <span>⏱ ${display_output.estimated_time}</span>
                    <span>📊 Difficulty: ${display_output.difficulty}</span>
                </div>
            </div>

            <div class="recipe-body">
                <div class="ingredients-list">
                    <h3>Synthesized Basis</h3>
                    <p style="color: var(--text-muted); line-height: 1.6;">${display_output.ingredients_used}</p>
                </div>

                <div class="instructions">
                    ${display_output.instructions.map((stepText, index) => {
            return `
                        <div class="step">
                            <div class="step-number">${index + 1}</div>
                            <div class="step-text">${stepText}</div>
                        </div>
                        `;
        }).join('')}
                </div>

                <div class="chef-note">
                    <strong>Chef Note:</strong> ${display_output.chef_note}
                </div>
            </div>
        `;

        recipeOutput.classList.remove('hidden');
    }
});
